# Get all contacts
GET http://localhost:5001/api/contacts

###

# Get contact for ID
GET http://localhost:5001/api/contacts/1

###

# Create contact
POST http://localhost:5001/api/contacts
Content-Type: application/json

{
  "name": "luis rodrigues",
  "email": "luis.rodrigues@email.com",
  "phone": "31984201068"
}

###

# Update contact for ID
PUT http://localhost:5001/api/contacts/2

###

# Delete contact for ID
DELETE http://localhost:5001/api/contacts/3
