### Get all contacts
GET http://localhost:5001/api/contacts

### Get contact for ID
GET http://localhost:5001/api/contacts/6478e8ff59ee51f92fe5a150

### Create contact
POST http://localhost:5001/api/contacts
Content-Type: application/json

{
  "name": "luis rodrigues",
  "email": "luis.rodrigues@email.com",
  "phone": "31984201068"
}

### Update contact for ID
PUT http://localhost:5001/api/contacts/6478e8ff59ee51f92fe5a150
Content-Type: application/json

{
  "name": "luis rodrigues up",
  "email": "luis.rodrigues.up@email.com",
  "phone": "31984201068"
}

### Delete contact for ID
DELETE http://localhost:5001/api/contacts/6478e8ff59ee51f92fe5a150
